version: 2

jobs:
  docs-build:
    docker:
      - image: python:3.6
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: pip install -r docs/requirements.txt
      - run:
          name: Build docs
          command: cd docs/ && make html
      - persist_to_workspace:
          root: docs/_build
          paths: html


  docs-deploy:
    docker:
      - image: node:8.10.0
    steps:
      - checkout
      - attach_workspace:
          at: docs/_build
      - run:
          name: Disable jekyll builds
          command: touch docs/_build/html/.nojekyll
      - run:
          name: Install and configure dependencies
          command: |
            npm install -g --silent gh-pages@2.0.1
            git config user.email "jimmy60504@gmail.com"
            git config user.name "jimmy60504"
      - run:
          name: Deploy docs to gh-pages branch
          command: gh-pages --dist docs/_build/html
      - add_ssh_keys:
          fingerprints:
            - "c5:ea:75:0f:91:a3:bb:bc:5e:92:3f:3e:6f:86:ad:ac"
      - run:
          name: Deploy docs to gh-pages branch
          command: gh-pages --dotfiles --message "[skip ci] Updates" --dist docs/_build/html


workflows:
  version: 2
  # If you have testing jobs, put them here...
  # testing:
  #   jobs:

  # All deployment
  build:
    jobs:
      - docs-build
      - docs-deploy:
          requires:
            - docs-build
          filters:
            branches:
              only: master