version: 2

jobs:
  docs-build:
    docker:
      - image: tensorflow/tensorflow:2.1.0-gpu-py3-jupyter
    steps:
      - checkout
      - run:
          name: Install linux dependencies
          command: |
            apt-mark hold libcudnn7
            apt-get update && apt-get upgrade -y
            apt-get install libproj-dev proj-data proj-bin libgeos-dev -y
      - run:
          name: Install python dependencies
          command: |
            pip uninstall -y enum34
            pip install -r docs/requirements.txt
      - run:
          name: Build docs
          command: cd docs/ && make html
      - persist_to_workspace:
          root: docs/_build
          paths: html

  docs-deploy:
    docker:
      - image: node:8.10.0
    steps:
      - checkout
      - attach_workspace:
          at: docs/_build
      - run:
          name: Disable jekyll builds
          command: touch docs/_build/html/.nojekyll
      - run:
          name: Install and configure dependencies
          command: |
            npm install -g --silent gh-pages@2.0.1
            git config user.email "bot@circleci.com"
            git config user.name "Circle CI"
      - run:
          name: Deploy docs to gh-pages branch
          command: gh-pages --dotfiles --message "[skip ci] Updates" --dist docs/_build/html
      - add_ssh_keys:
          fingerprints:
            - "a1:8f:df:5f:7a:da:e9:82:21:3c:c1:b1:45:dd:10:de"


workflows:
  version: 2
  build:
    jobs:
      - docs-build
      - docs-deploy:
          requires:
            - docs-build
          filters:
            branches:
              only: master